# Codex CLI configuration for this repository.
# This file is used by tools/sqa_runner.py to run the SQA plan with a
# deterministic profile checked into the repo.

# Default provider is OpenAI; set OPENAI_API_KEY in your environment.
# You can also override provider base_url via OPENAI_BASE_URL if needed.

[profiles.sqa]
# Model and behavior
model = "gpt-5"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
model_verbosity = "high"
approval_policy = "never"        # no prompts

# Sandbox: write access to workspace and allow outbound network
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true

# Optional: enable built-in web search tool if desired
[tools]
web_search = true

